version: '3.3'
services:
  db_pg:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    networks:
      some_network:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db_pg

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../backend/:/app/result_build/
    depends_on:
      - frontend
      - db_pg
    links:
        - db_pg:db_pg
    env_file:
      - ../.env
    #command: bash -c "python manage.py migrate"
    networks:
      some_network:

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      # Контейнер nginx должен быть запущен после контейнера web
      - backend
    networks:
      some_network:

networks:
  some_network:
