# Generated by Django 2.2.19 on 2022-06-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220611_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=1, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
