# Generated by Django 2.2.19 on 2022-06-17 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220615_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_favoutites', to=settings.AUTH_USER_MODEL, verbose_name='favourites'),
        ),
    ]
