# Generated by Django 2.2.19 on 2022-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220618_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(verbose_name='tags_slug'),
        ),
    ]
