# Generated by Django 2.2.19 on 2022-06-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220607_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_following',
        ),
    ]
